### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by shanguangcv** [zhiyuanyou/SAFECount#1]
Hi, thanks for your good work, I am trying to reproduce your method. When I train by running (./train_torch.sh #Num_GPUS), if I use one GPU (i.e., ./train_torch.sh 1), the network can be trained. However, if I use more gpus (e.g., ./train_torch.sh 2), it will shows that "RuntimeError: Address already in use".  
Moreover, I have tried to change the master_port, but it is still wrong.

**Comment by zhiyuanyou** [comment]
Hi～
I will fix it soon.

**Comment by zhiyuanyou** [comment]
Hi~ 
We have fixed this bug. Please try again. 
If you use 2 GPU, you could run `sh train_torch.sh 2 GPU_IDS`, where GPU_IDS is the ID of the GPU you will use, like 0,1.
