### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Lay-best** [zhiyuanyou/SAFECount#10]
When I run the file train_val.py, but I meet a error below .How I resolve it?
`Traceback (most recent call last):
  File "E:\python code\SAFECount-main\tools\train_val.py", line 325, in <module>
    main()
  File "E:\python code\SAFECount-main\tools\train_val.py", line 43, in main
    with open(args.config) as f:
FileNotFoundError: [Errno 2] No such file or directory: './config.yaml'

Process finished with exit code 1`

**Comment by zhiyuanyou** [comment]
- 你应该进入到实验路径以下，再运行代码。例如：
首先运行`cd ./experiments/FSC147/`
之后运行`train.sh`

- 如果你不想进入实验路径之下，则需要在`train.sh`中指定config路径，例如：
`python -m torch.distributed.launch --nproc_per_node=$1 ../../tools/train_val.py --config experiments/FSC147/config.yaml`
