### ISSUE TITLE
I can't create the dataset the FSC147 dataset directory

### ISSUE THREAD

**Issue by Lay-best** [zhiyuanyou/SAFECount#11]
I can't create the dataset the FSC147 dataset directory. Because there aren't file 'images_384_VarV2' and 'gt_density_map_adaptive_384_VarV2' in the FSC147 dataset file which I downloade in the offical github website

**Comment by zhiyuanyou** [comment]
**_images_384_VarV2_** is here: https://drive.google.com/file/d/1ymDYrGs9DSRicfZbSCDiOu0ikGDh5k6S/view
**_gt_density_map_adaptive_384_VarV2_** is here: https://archive.org/download/FSC147-GT/gt_density_map_adaptive_384_VarV2.zip
