### ISSUE TITLE
how to genenrate FS

### ISSUE THREAD

**Issue by 1105905317** [zhiyuanyou/SAFECount#17]
hello, I read your paper, in the paper the support feature(FS) is obtained by applying ROI pooling on the feature extracted from its parent before cropping,but in the code is exemplar.json,which contain coordinate(is ROI?), how to genenrate exemplar.json and what's means. looking forward to your reply,thanks!

**Comment by zhiyuanyou** [comment]
Hi~

We provide codes for ***both*** cases: 
- the support images are crop from the query image.
- the support images are independent small image. 

Please see ***circumstance*** in Sec. 2 of README.
