### ISSUE TITLE
The train pipeline for CARPK dataset

### ISSUE THREAD

**Issue by shanguangcv** [zhiyuanyou/SAFECount#2]
Hi, in cross-dataset (CARPK) experiment, you pre-train the model on FSC-147, can you provide a pre-train script? Moreover, can you also provide a fine-tune script for easy use? Thanks.

**Comment by zhiyuanyou** [comment]
Hi~ 

This needs some time to re-organize. 

The main reason is that the settings of FSC147 & CARPK are different: for FSC147, exemplars are parts of the query image, for CARPK, exemplars are sampled from the training set and fixed for both training and evaluation. 

We hope provide this in this week.

**Comment by shanguangcv** [comment]
Thanks

**Comment by zhiyuanyou** [comment]
Hi~
We have provided the pretrain and finetune script.
