### ISSUE TITLE
Hello , I coudn't found the Similarity Comparison Module (SCM) and the Feature Enhancement Module (FEM) in your code.

### ISSUE THREAD

**Issue by Msmy512** [zhiyuanyou/SAFECount#21]
Could you please tell me where are these module  in your code?

**Comment by zhiyuanyou** [comment]
calculate similarity (attention): https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount.py#L195
score normalization: https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount.py#L225
similarity weighted aggregation: https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount.py#L236
fuse feature: https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount.py#L153
