### ISSUE TITLE
How to test the code using this tools/train_val.py   ?  

### ISSUE THREAD

**Issue by vasanth4224** [zhiyuanyou/SAFECount#23]
When I try to execute the train_val.py , I got this error.

Traceback (most recent call last):
  File "tools/train_val.py", line 12, in <module>
    from datasets.data_builder import build_dataloader
ModuleNotFoundError: No module named 'datasets'

**Comment by zhiyuanyou** [comment]
Please see https://github.com/zhiyuanyou/SAFECount/issues/18
