### ISSUE TITLE
About cross-dataset setting

### ISSUE THREAD

**Issue by kangyeolk** [zhiyuanyou/SAFECount#31]
Hi, 

Thank you for sharing wonderful work!

Could you elaborate the performance differences between safecount.py (when initializing fsc146 pre-trained model) and safecount_crossdataset.py ?

**Comment by zhiyuanyou** [comment]
In FSC-147, there are exemplar boxes, so we crop the feature map in each layer for better enhancement. 
But for CARPK, there are no exemplar boxes, only small exemplar images, we can not crop the feature map in each layer. 

So the implementations of these two models are different. Directly transferring weights suffers from poor performance.

**Comment by kangyeolk** [comment]
Okay, I'm trying to train my own model with custom dataset (600 images with boxes). 
In my understanding then, is it more proper to use safecount.py model?

Another question is that my data doesn't vary much in object size with distance. What do you think about standardizing the heatmap size uniformly?

Thank you :)

**Comment by zhiyuanyou** [comment]
I think it is more proper to use the `safecount.py` model. 
I did not get the meanings of "doesn't vary much in object size with distance". Could you give some examples?

**Comment by kangyeolk** [comment]
Ah, ignore what I said above. My question is about the heatmap size being determined by the size of the bounding box. In the gen_gt_density.py part, since the radius is set based on a single bounding box, the heatmap sometimes gets quite large. Actually, in my data, the objects are thin, so it seems more appropriate to arbitrarily set the heatmap smaller, but I'm wondering if this will affect the training.

After training and conducting inference, I noticed that if even one object in the image is large, the heatmap tends to be larger overall.
![image](https://github.com/zhiyuanyou/SAFECount/assets/26561999/d17e59e3-1ddb-4f3c-9f51-baac9a84a5e4)
![image](https://github.com/zhiyuanyou/SAFECount/assets/26561999/305b4b85-aa48-43e3-b0fa-e3bdf5be54a5)

**Comment by zhiyuanyou** [comment]
This could be a question. 

I am not sure which one (larger or smaller focus) could be better. You can do experiments to compare.

**Comment by kangyeolk** [comment]
Okay, thank you for your kind answer!
