### ISSUE TITLE
How to execute without slurm installed

### ISSUE THREAD

**Issue by junjun1023** [zhiyuanyou/SAFECount#32]
Hi, I'm trying to run `test.sh` under `/experiments/FSC147`, but it shows that 
`s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf`

Is it possible to execute on a single PC without using distributed system?
How can I modified to run on my PC?

**Comment by zhiyuanyou** [comment]
Please use [test_torch.sh](https://github.com/zhiyuanyou/SAFECount/blob/main/experiments/FSC147/test_torch.sh)
