### ISSUE TITLE
About support image

### ISSUE THREAD

**Issue by junjun1023** [zhiyuanyou/SAFECount#33]
I appreciate your excellent work.

What confuses me is where the support images are read and fed to network and extract feature?

Thank you for the response.

**Comment by zhiyuanyou** [comment]
In FSC-147 dataset, the support images are crop from the original image. Thus we only input the bounding boxes to the networks, as shown in https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount.py#L56.

**Comment by zhiyuanyou** [comment]
In other datasets, the support images are used in https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount_exemplar.py#L58 and https://github.com/zhiyuanyou/SAFECount/blob/main/models/safecount_exemplar.py#L59.
