### ISSUE TITLE
question on the use of few shot images

### ISSUE THREAD

**Issue by limshanshan** [zhiyuanyou/SAFECount#35]
Hi, may I know for the FSC147 to CARPK experiment, after I pretrain the model, must I finetune it or can I go straight to eval? If I finetune it, won't the unseen class be exposed to the model? Also, is there support images used during eval or finetuning?

**Comment by zhiyuanyou** [comment]
1. Both pre-trained model and fine-tuned model are tested. 
2. Yes. The unseen class will be exposed to the model during the fine-tuning stage. 
3. Yes. There are support images used during eval or fine-tuning.

**Comment by limshanshan** [comment]
ok thank u :)

**Comment by limshanshan** [comment]
Hi, for FSC147 to CARPK experiment, do I have to manually exclude the car images during training using FSC147?

**Comment by zhiyuanyou** [comment]
Yes.

**Comment by limshanshan** [comment]
ok, thank u!
