### ISSUE TITLE
exemplar.json

### ISSUE THREAD

**Issue by HandsLing** [zhiyuanyou/SAFECount#37]
您好，我的训练数据只有rgb图像以及对应每个目标的一个[x,y]的中心点作为标注，请问exemplar.json这个文件要怎么生成呢？以及这个文件的意义是什么呢？我只想获得每张图片的人群密度

**Comment by zhiyuanyou** [comment]
Hello，如果是人群计数的话，不建议采用小样本计数算法，建议直接用人群计数算法，精度会高很多。
