### ISSUE TITLE
Visualization & post processing

### ISSUE THREAD

**Issue by jaideep11061982** [zhiyuanyou/SAFECount#4]
@zhiyuanyou 
I am  viewing the below density dotted image. How can we interpret which heatmapped dot are likely to be counted.
Currently I do simply output.sum() ,is there any way i can do sum based on some threshold value which indicates high likelyhood of an object count ?

![image](https://user-images.githubusercontent.com/38164196/208101956-daf1ae80-bf39-4f61-afa7-3995c78d87a6.png)

**Comment by zhiyuanyou** [comment]
Actually, you ***could not find the accurate localization of the counted objects***, since this method is density-based. If you wanna count objects by accurately localizing objects, you should seek to some point-based methods.

**Comment by jaideep11061982** [comment]
@zhiyuanyou do you have any pointers,
but density labels that were chose for the models  training were point based only

**Comment by zhiyuanyou** [comment]
If you wanna find ***the accurate localization of the counted objects***, I recommend P2PNet, which is 
https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet.

If you try to reproduce P2PNet, please ***pay attention to the following bug*** (which is I find during my reproduction)
https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet/issues/48
