### ISSUE TITLE
How different is this paper

### ISSUE THREAD

**Issue by jaideep11061982** [zhiyuanyou/SAFECount#6]
https://arxiv.org/pdf/2211.08217v1.pdf

@zhiyuanyou  could you read through this once. author has explained the logic .
for attention feature they are using I think Transformer encoder layer . Later part not clear to me.
So wanted to understand if there is big or minor difference between your paper and this new one

**Comment by zhiyuanyou** [comment]
Well, I had read this paper in the past. I think this paper proposes a better method considering its outstanding performance.

**Comment by jaideep11061982** [comment]
@zhiyuanyou any small help I can get in implementing its Object protoptype extraction part, It appears analogous to your Safe count block logic 
After reading through this paper , it appears they use Resnet 50 as backbone followed by Multiheaded attention module  which then inputs to Object prototype extraction module

**Comment by zhiyuanyou** [comment]
It is better to contact the authors for their code.
