### ISSUE TITLE
Hello, how to generate the train.json file for training your own dataset

### ISSUE THREAD

**Issue by 1274739295** [zhiyuanyou/SAFECount#7]
We would like to train our own dataset after reproducing your paper. I wonder if you can provide us with the train.json of how to generate our own dataset, and if you can tell us how to get the mask.png file in the mall dataset?

**Comment by zhiyuanyou** [comment]
1. There are two kinds of _train.json_:
- Annotated with boxes. In this case, you should annotate your own data with boxes circled every object (_e.g._, [train.json](https://github.com/zhiyuanyou/SAFECount/blob/main/data/CARPK_devkit/train.json)).
- Annotated with points. In this case, you should annotate your own data with points in every object center (_e.g._, [train.json](https://github.com/zhiyuanyou/SAFECount/blob/main/data/ShanghaiTech/part_A/train.json)).

After annotation, you could generate a json file just following the structure of _train.json_. 

2. The ***mask.png*** is under the [Mall dataset](http://personal.ie.cuhk.edu.hk/~ccloy/downloads_mall_dataset.html), (_i.e._, ***perspective_roi.mat***). I did some transformation to  transform it to a png image.
